name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - run: go install golang.org/x/mobile/cmd/gomobile@latest && go env && gomobile init && make all
