name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  actions: write
  contents: write
  packages: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Build
        id: build
        run: bash scripts/github/workflows/build.sh

      - name: Upload To Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          name: vtun
          path: ${{ steps.build.outputs.buildoutputs }}/*

      - name: Upload To Release
        id: release
        uses: softprops/action-gh-release@v2
        if: steps.build.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          files: ${{ steps.build.outputs.buildoutputs }}/*

      - name: Delete workflow runs
        id: workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 1

