name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Build
        id: build
        run: bash scripts/github/workflows/build.sh

      - name: Upload To Artifact
        uses: actions/upload-artifact@v4
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          name: vtun
          path: ${{ steps.build.outputs.buildoutputs }}/*
      